baseURL = "https://badasstronaut.github.io/"
title = "Badasstronaut Solutions"
languageCode = "en-us"
theme = "hugo-theme-m10c"

[Params]
    author = "Mickey"
    avatar = "img/me_pic.png"
    description = "Mickey's personal site"
    logo = "favicon/android-chrome-192x192.png"
    twitterAuthor = "@_badasstronaut"
    githubUsername = "badasstronaut"
    accent = "#0f283d" # dark colors do best
    backgroundColor = "#f5f5f5"
    font = "Source Code Pro" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark" # make this match accent
    highlightLanguages = ["javascript", "bash"]
    css = ["css/custom.css"]

[[Params.social]]
    icon = "linkedin"
    url = "https://www.linkedin.com/in/kylemickey/"
    name = "linkedin"

[[Params.social]]
    icon = "github"
    url = "https://github.com/badasstronaut"
    name = "github"

[[Params.social]]
    icon = "mail"
    url = "mailto:kyle.mickey@gmail.com"
    name = "email"

[[menu.main]]
    url = "/"
    name = "home"
    weight = 1

[[menu.main]]
    url="/about-me"
    name="about me"

[[menu.main]]
    url = "/articles"
    name = "articles"

[[menu.main]]
    url = "/resume"
    name = "resume"
