baseURL = "https://badasstronaut.github.io/"
title = "Badasstronaut Solutions"
languageCode = "en-us"
theme = "hugo-theme-m10c"

[Params]
    author = "Mickey"
    avatar = "icons/badasstronaut.svg"
    description = "Mickey's personal site"
    menu_item_separator = "|"

[[Params.social]]
    icon = "linkedin"
    url = "https://www.linkedin.com/in/kylemickey/"
    name = "linkedin"

[[Params.social]]
    icon = "github"
    url = "https://github.com/badasstronaut"
    name = "github"

[[Params.social]]
    icon = "mail"
    url = "mailto:kyle.mickey@gmail.com"
    name = "email"

[[menu.main]]
    url="/about-me"
    name="about me"

[[menu.main]]
    url = "/articles"
    name = "articles"

[[menu.main]]
    url = "/resume"
    name = "resume"

[markup.goldmark.renderer]
unsafe = true
