baseURL = "https://badasstronaut.github.io/"
languageCode = "en-us"
title = "Badasstronaut Solutions"
theme = "min_night"

[Params]
    author = "Kyle Mickey"
    description = "Mickey's personal site"
    logo = "favicon/android-chrome-192x192.png"
    twitterAuthor = "@_badasstronaut"
    githubUsername = "badasstronaut"
    accent = "#0f283d" # dark colors do best
    backgroundColor = "#f5f5f5"
    font = "Source Code Pro" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark" # make this match accent
    highlightLanguages = ["Docker", "Nodejs", "C#", "React", "Redux", "SQL", "NoSQL"]


[[menu.main]]
    url = "/"
    name = "home"
    weight = 1

[[menu.main]]
    url = "/articles"
    name = "articles"


[[menu.icon]]
    url = "mailto:kyle.mickey@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/badasstronaut"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/_badasstronaut/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/kylemickey/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://stackoverflow.com/users/4175701/badasstronaut"
    name = "stack-overflow"
    weight = 5
